### ISSUE TITLE
Multitenant version using central portal?

### ISSUE THREAD

**Issue by sbarzaghialteaup** [SAP-samples/multi-cloud-html5-apps-samples#11]
Hi,

Do you have a multitenant version using the central portal?
I mean a sample to provide an app as "content provider" and how to consume the app in the subscriber subaccount.

Thanks
Sam

**Comment by IObert** [comment]
Hi,

I don't have such a sample at hand right now but I'll try to find one / to find out if that's possible. Stay tuned!

Marius

**Comment by sbarzaghialteaup** [comment]
Hi Marius,

In the meantime I started implementing it.
The mta is done, db created during subaccounts subscription it's ok, apps are availables in the subscriptor central portal  and I can start launchpad portal with my saas app.

However I have a problem with the very last step, elements fiori apps with tables don't start:
https://answers.sap.com/questions/13158208/fiori-elements-multitenant-error-viewswitchcontain.html
I'm investigating.

In local and in single tenant deployment metadata are ok, deploying in multitenant mode the metadata generated by CAP are missing all the UI annotations.
![image](https://user-images.githubusercontent.com/51169423/95548235-ec90ed80-0a04-11eb-9d43-747ef6b77a3c.png)

When finished, if you like, I can share you the github repository.

Thanks

Ciao
Sam

**Comment by arilulu** [comment]
Hi, did you consider using a business service for content sharing:
https://help.sap.com/viewer/ad4b9f0b14b0458cad9bd27bf435637d/Cloud/en-US/bf7d98cf76df48009d8bc88599b6cd55.html

**Comment by sbarzaghialteaup** [comment]
Hi arilulu sorry I can't understand your suggestions, partners can publish SCP business services?

However the multitenant cap application with apps published in central portal is up and running with two subscribers.
I can share a very simple sample if usefull.

**Comment by gregorwolf** [comment]
Please do so.

**Comment by arilulu** [comment]
Hi @sbarzaghialteaup,
Maybe you can share more details on the complete scenario.
Currently, it is only possible to define and expose a business service to all spaces in a subaccount.
It is not possible to publish it to the marketplace.

**Comment by sbarzaghialteaup** [comment]
> Please do so.

Here we are:
https://github.com/sbarzaghialteaup/cap-multitenant-portal

ciao

**Comment by sbarzaghialteaup** [comment]
> Hi @sbarzaghialteaup,
> Maybe you can share more details on the complete scenario.
> Currently, it is only possible to define and expose a business service to all spaces in a subaccount.
> It is not possible to publish it to the marketplace.

We are developing a saas application to resell to our customers.

**Comment by aliasad466** [comment]
Hi,
I am looking for a solution that we deploy a portal in provider account that has fiori UIs, and those fiori UIs along with portal has to available in subscriber account. What I can achieve with this is to have the portal apps as content provider, but I want to skip this step. Is it possible and if so, how?

**Comment by nicoschoenteich** [comment]
Hi there @aliasad466!
Do I get this question right, that you want to deploy a whole portal with multiple apps and make these available to subscribing subaccounts? What exactly is the step you want to skip?
How is this different to the example what already @sbarzaghialteaup shared?

**Comment by aliasad999** [comment]
Hi,
Well I have figured a solution for now. 
Only change from the example above is that if you want to have portal available instead of providing content to central portal. You need to change the url to approuter when tenant registers and you need to create a dependency to cloud portal service in saas get dependencies endpoint. 

Please ignore typos in the text

**Comment by aliasad999** [comment]
> Hi there @aliasad466!
> Do I get this question right, that you want to deploy a whole portal with multiple apps and make these available to subscribing subaccounts? What exactly is the step you want to skip?
> How is this different to the example what already @sbarzaghialteaup shared?

Hi,
Well I have figured a solution for now.
Only change from the example above is that if you want to have portal available instead of providing content to central portal. You need to change the url to approuter when tenant registers and you need to create a dependency to cloud portal service in saas get dependencies endpoint.

Please ignore typos in the text
