### ISSUE TITLE
What version of the cf cli are you using: `cf html5-list`

### ISSUE THREAD

**Issue by js1972** [SAP-samples/multi-cloud-html5-apps-samples#13]
If I use command `cf html5-list` as you show in the readme it says:
```
'html5-list' is not a registered command. See 'cf help -a'
```

I'm on  cf version 7.0.2+17b4eeafd.2020-07-24.

**Comment by vbalko** [comment]
You have to add HTML5 plugin to CF - see [https://sap.github.io/cf-html5-apps-repo-cli-plugin/](url)
