### ISSUE TITLE
Correct warning in managed-html5-runtime-fiori-mta example makes app unavailable in Launchpad Content Manager

### ISSUE THREAD

**Issue by gregorwolf** [SAP-samples/multi-cloud-html5-apps-samples#17]
Hi Marius,

with the current configuration of the managed-html5-runtime-fiori-mta example I get the following warning during deployment:

> [WARNING] Destinations content in module managed-fiori-destination-content is defined in a deprecated location (in a parameter of a requires element). Move the content parameter from the requires parameters to the modules parameters.

but when I correct that by moving the content section as I did in the [pull request](https://github.com/SAP-samples/multi-cloud-html5-apps-samples/pull/16/commits/6d5e501de5219dcaf45c866309e6001312b5da3e), the error is gone, but the app isn't available in Launchpad Content Manager anymore. Can you clarify this issue internaly?

Best regards
Gregor

**Comment by IObert** [comment]
Will do. Thanks Gregor

**Comment by IObert** [comment]
Hi Gregor,

You might have seen the fix from @ddonchev to your PR. I think that resolves the issue you found, correct?
I also updated the Fiori Sample with the same fix in @multi-cloud-html5-apps-samples@8c234ed

**Comment by IObert** [comment]
I'll close this one as it seems to be fixed. Please reopen if you disagree.
