### ISSUE TITLE
managed-html5-runtime-fiori-mta app doesn't fetch information from Northwind service

### ISSUE THREAD

**Issue by manjunathgudisi** [SAP-samples/multi-cloud-html5-apps-samples#18]
Hi

After I deploy the **managed-html5-runtime-fiori-mta** onto my SCP accont. This is how it looks.
<img width="1641" alt="Screen Shot 2020-10-18 at 1 06 13 PM" src="https://user-images.githubusercontent.com/6059076/96361433-43a06c00-1143-11eb-8b36-4b7c73118cd0.png">
<img width="1678" alt="Screen Shot 2020-10-18 at 1 06 57 PM" src="https://user-images.githubusercontent.com/6059076/96361437-4733f300-1143-11eb-9717-d04572a8ba7e.png">
<img width="1190" alt="Screen Shot 2020-10-18 at 1 11 05 PM" src="https://user-images.githubusercontent.com/6059076/96361455-66328500-1143-11eb-989e-e6c2de71a090.png">

When I run the app, it's not showing any content in the app. What's the reason?

Just FYI, I didnt change anything in the **mta.taml** file located in **multi-cloud-html5-apps-samples/managed-html5-runtime-fiori-mta/**

Thanks, Manju

**Comment by IObert** [comment]
Hi,

it actually looks are good. Did you select all available columns via the Gear button and click "Go" to display them?

**Comment by IObert** [comment]
I'll close this for now. Please reopen if the issue still persists
