### ISSUE TITLE
Fails to 'make'

### ISSUE THREAD

**Issue by piejanssens** [SAP-samples/multi-cloud-html5-apps-samples#2]
```
➜  html5-app-repo-router (master) ✔ make -f Makefile.mta p=cf   
[2019-10-27 13:53:26]  INFO validating the MTA project
[2019-10-27 13:53:26] ERROR could not validate the "/Users/pieter/Projects/html5-app-repo-router/paths" file: failed to read the "/Users/pieter/Projects/html5-app-repo-router/paths" file: open /Users/pieter/Projects/html5-app-repo-router/paths: no such file or directory
make: *** [pre_validate] Error 1
```
Has to do something with this line 
https://github.com/SAP-samples/html5-app-repo-router/blob/d248fcccf50ddc1d4b729411147124e529a1834b/Makefile.mta#L28

```
➜  html5-app-repo-router (master) ✔ make --version
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0
```

**Comment by piejanssens** [comment]
Was able to get passed this error by omitting `-e="paths"`.

**Comment by IObert** [comment]
Thanks for opening the issue. 

This is strange. Can you try to run `mbt build -p=cf` instead of the make command?

**Comment by piejanssens** [comment]
That works (I tested with after referting my change in Makefile.mta).

**Comment by IObert** [comment]
Ok, I updated the instructions to use the mbt build command directly. If you are able to reproduce this issue, please open a new issue for the [build tool](https://github.com/SAP/cloud-mta-build-tool).

I think this is not related to this project here
