### ISSUE TITLE
How can I redirect requests to /appconfig/fioriSandboxConfig.json to my HTML5 repo

### ISSUE THREAD

**Issue by gregorwolf** [SAP-samples/multi-cloud-html5-apps-samples#20]
Hi @IObert,

in my CAP sample project [bookshop-demo](https://github.com/gregorwolf/bookshop-demo) I'm using the file [appconfig/fioriSandboxConfig.json](https://github.com/gregorwolf/bookshop-demo/blob/master/app/webapp/appconfig/fioriSandboxConfig.json). When I pass the path to that file via the URL parameter "sap-ushell-sandbox-config" i.e.:

> /bookshopdemoapp/fiori-latest.html?sap-ushell-sandbox-config=./appconfig/fioriSandboxConfig.json#Shell-home

everything is fine. But I want to avoid that parameter and rely on the default behaviour. There, the file is searched at "/appconfig/fioriSandboxConfig.json":

![Screenshot 2020-10-20 at 08 39 48](https://user-images.githubusercontent.com/2639535/96549614-05748b00-12b0-11eb-8bc1-6756177e4a27.png)

is there a way that I can configure the xs-app.json in either the approuter or my HTML5 repository to resolve /appconfig/ to the correct folder in my HTML5 repository?

Best regards
Gregor

**Comment by IObert** [comment]
Hi Gregor,

I haven't tried that specific scenario yet but I have used routes that point to specific files. It should definitely work with the approuter and probably also with the "inner xs-app.json".

Try the following route:
```
"routes": [
		{
			"source": "^/appconfig/fioriSandboxConfig.json",
			"target": "/fioriSandboxConfig.json",
			"localDir": "appconfig"
		}
	]
```

**Comment by IObert** [comment]
I'll close this now. Please reopen if this doesn't work.
