### ISSUE TITLE
Sample managed-html5-runtime-fiori-mta not displayed once added in Launchpad

### ISSUE THREAD

**Issue by sammok83** [SAP-samples/multi-cloud-html5-apps-samples#21]
Hi @IObert ,

Followed the simple steps detailed in https://github.com/SAP-samples/multi-cloud-html5-apps-samples/tree/master/managed-html5-runtime-fiori-mta and it works if using this structure:

https://[globalaccount-id].launchpad.cfapps.[region].hana.ondemand.com/cloudservice.comsapfioriapp/index.html#Shell-home

However it doesn't work when accessing it from launchpad after adding it: 
![1](https://user-images.githubusercontent.com/10509241/97257980-79dc9a80-186b-11eb-8e63-507e549ed870.jpg)

Thanks.

**Comment by IObert** [comment]
Can you please be more specific about what you mean by "access it from launchpad"?

Did you use the "Add to My Content" button and add the app to a role and a group?

**Comment by sammok83** [comment]
Yes I did. Twice. Accessing it by clicking on a tile which I've added on the launchpad service

**Comment by IObert** [comment]
That is strange, it does work for me. I just double-checked it. Can you confirm that you followed [these steps](https://developers.sap.com/tutorials/cp-launchpad-integrate-sapui5-app.html) with the original sample (with no modifications).

**Comment by sammok83** [comment]
@IObert Yes, I'm trying it for the 4th time and it still doesn't work. (Deleting and Redoing everything - including changing the description to make sure it's not reading from the old cache). The steps are simple and straightforward and it works using index.html as above but it doesn't work when launched from the launchpad.

Other details:
Google Chrome: Version 86.0.4240.111 (Official Build) (64-bit)

Here's more info on my console:
![1](https://user-images.githubusercontent.com/10509241/97289018-c1c6e600-189a-11eb-87e1-34a21a0342d7.jpg)

Maybe try with the Trial account?

**Comment by IObert** [comment]
Weird,
I'll reach out internally to see if someone can help.

**Comment by urigeva93** [comment]
Hi,

Did you try to reload the site with "Disable Cache" option (using DevTools) or deleting browser cache before that?
 
Anyway, can you please provide me the following info for investigation:
 
1. Full Landscape details (is it us10?)
2. Access the site again, and in the failed request, go to "Headers" and -> "response headers" section and provider the value 
    of the "X-Vcap-Request-Id" (if exists).
3. Absolute time of step 2. 

Thanks

**Comment by sammok83** [comment]
Hi @urigeva93 ,

I've always check Disable cache (Chrome Debugger console > Network Tab) as a habit. Even tried in Microsoft Edge - but with the same result.

1. Org Name: 2963c574trial
    Org ID: 0b2dca1b-56ea-4c1c-98f7-e6845a669679
    API Endpoint: **https://api.cf.us10.hana.ondemand.com**
2. X-Vcap-Request-Id: **f9bd5fe6-70c5-4dbd-68e7-e10e59698e5d**
3.
![Time](https://user-images.githubusercontent.com/10509241/97373275-b52da680-1909-11eb-8c41-bbd0974043b2.jpg)

**Comment by urigeva93** [comment]
Hi,

Thanks for your input. Can you also please tell me what is the (absolute) time where you try to access the site (for logging filtering purposes).

**Comment by sammok83** [comment]
New X-Vcap-Request-Id: 97ba0cc1-a818-4dfc-5ebc-5fd68b5c8d4b
Date: Wed, 28 Oct 2020 11:12:21 GMT

**Comment by urigeva93** [comment]
Hi,

I started to investigate this and I indeed see a 400 Bad request in our logs. Since it's a live system, in order for me to see additional logs (that would help me analyze the issue), I need to handle this internally. @IObert - Can you plase raise a BCP ticket under the Component: "EP-CPP-CF-LP-DEV"?

Thanks

**Comment by IObert** [comment]
Done, you can find it under Internal Incident: 2070444677

**Comment by IObert** [comment]
I've been told the issue has been resolved and the fix should come with the next deployment in two weeks. Please let us know if it works then.

**Comment by IObert** [comment]
Can you please try again and see if the issue is resolved?

**Comment by sammok83** [comment]
@IObert I still get the same error as in my first post.

**Comment by IObert** [comment]
Thanks. I'll send it back to the team.

**Comment by yaronp** [comment]
Hi @sammok83 ,

We would like to investigate this issue deeper using updated tools. 
Can you please reproduce for us and send us the **correlation id** so we can dig deeper?

Thanks,
Yaron Pdut, Portal R&D

**Comment by IObert** [comment]
I'll close this one due to inactivity. Please reopen if you still see the issue.
