### ISSUE TITLE
501 Bad Gateway on the Northwind Service

### ISSUE THREAD

**Issue by js1972** [SAP-samples/multi-cloud-html5-apps-samples#22]
Hi. I have used this sample (the fiori one) a few weeks ago and it was working fine. I am testing it again and have pulled the lastest `master` branch but it is unable to reach the OData service. the app fails with `502 Bad Gateway` when it tries to read the $metadata. Any ideas?

I have created another test application using fiori-tools and connected it to the Northwind OData service. I notice that this does not work anymore either and gives certificate errors in the browser console unless I make this setting in the fiori-tools-proxy:
```
configuration:
        ignoreCertError: true
```
...in which case its starts working.

I'm wondering if something is wrong with the https://services.odata.org certificate. Are you able to run this app and fetch data ok today?

**Comment by IObert** [comment]
Hi,

this is really strange. Which sample are we talking about? I'll test it then.

**Comment by js1972** [comment]
Sorry. It's the fiori one.

**Comment by IObert** [comment]
Which Fiori one :) ? (managed or standalone)

**Comment by IObert** [comment]
I just tested the managed Fiori app and you are right. It seems that the Northwind service currently has issues. You can also see that here: <https://services.odata.org/V2/Northwind/Northwind.svc/>

<img width="715" alt="Screen Shot 2020-10-30 at 10 59 00" src="https://user-images.githubusercontent.com/1873245/97691649-ec818c00-1a9e-11eb-9226-e41b62c6f08a.png">

I'd assume Microsoft will fix this soon and therefore I wouldn't do a change in the repo now. But that's definitely worth having an eye on, thanks for bringing this up!

**Comment by IObert** [comment]
Seems like the issue has already been reported here: OData/odataorg.github.io#255

**Comment by js1972** [comment]
Sap-managed fiori.

**Comment by js1972** [comment]
I think it's a bad cert on the north wind service because it won't work when running locally unless I say ignore cert errors in the ui5.yaml file. So it seems the destination can't handle it though....

**Comment by js1972** [comment]
Closing - Microsoft seem to have fixed the cert issue. Unfortunately when I go back through all the incidents for the service it seems that it regularly gets these issues.  ;-(. This is the sort of thing that *always* happens when you are doing a demo of course!

Thanks for your help.

**Comment by IObert** [comment]
I'm glad it's working again. Tip: You can also use the ES5 system in case you run into an issue with Northwind in the future.
