### ISSUE TITLE
Issues with HTML5 Destination URL in Feature Set B Account

### ISSUE THREAD

**Issue by AgilitaDaniel** [SAP-samples/multi-cloud-html5-apps-samples#23]
While trying to setup the "managed-html5-runtime-basic-mta" example I am not able to retrieve the URL like described in step 5.

The App is visible within the **CF HTML5-LIST** command but when trying to run **cf html5-list -di hello-world_ui_deployer -u** I get the following error:

**_Could not find service instance of 'destination' service 'lite' plan with name 'hello-world_ui_deployer'_**

**Comment by IObert** [comment]
Hi,

good point! It should obviously be`cf html5-list -di hello-world-destination-service -u` instead. I'll fix this momentary. 

Thanks a lot!
