### ISSUE TITLE
Destination configuration issue

### ISSUE THREAD

**Issue by mihaileb** [SAP-samples/multi-cloud-html5-apps-samples#25]
Following the example, creating the destination service for managed html5 runtime fails due to the destination configuration:
      config:
        HTML5Runtime_enabled: true
        version: 1.0.0
This config fails on creation

**Comment by IObert** [comment]
Hi,

thanks for opening the issue, that shouldn't happen. Which sample is causing the problem and to which environment (trial/prod) are you trying to deploy?

**Comment by mihaileb** [comment]
> Hi,
> 
> thanks for opening the issue, that shouldn't happen. Which sample is causing the problem and to which environment (trial/prod) are you trying to deploy?

Thanks for replying so fast.
I am trying in a trial account, but like to test this also in a productive system for a customer.

**Comment by IObert** [comment]
Which sample did you try?

**Comment by mihaileb** [comment]
> Which sample did you try?

The managed fiori mta. https://github.com/SAP-samples/multi-cloud-html5-apps-samples/tree/master/managed-html5-runtime-fiori-mta
Tried everything and is not working. imported also destinations.
Checked also this ticket : https://launchpad.support.sap.com/#/notes/0002965719
Still, the parameters in the destinations HTML5Runtime_enabled: true is not working. Also cli and also default BAS template project with managed approuter not working.
Thank you

**Comment by IObert** [comment]
I can confirm that it doesn't work for me either. That seems to be a technical issue on the platform but this property is needed.

**Comment by IObert** [comment]
It should be resolved now. Please reopen otherwise
