### ISSUE TITLE
logout functionality

### ISSUE THREAD

**Issue by aman-bal** [SAP-samples/multi-cloud-html5-apps-samples#26]
Hi,

Does the logout functionality really work. To make a user fully logout, is there something extra needed ?

Thanks
Aman

**Comment by IObert** [comment]
I just checked and it seems that is feature is implemented for some but not all samples. Which sample are you referring to?

**Comment by aman-bal** [comment]
https://github.com/SAP-samples/multi-cloud-html5-apps-samples/tree/master/standalone-mtx-approuter

**Comment by IObert** [comment]
Ah, yes. Good catch!
So the logout was fully working but there was a problem with the "Successfully logged out" page that was shown afterward. This page accidentally caused that you were logged back in via SSO again.

I fixed it and it should work now. E.g. no following request will be able to pass an "xsuaa" route before logging in again.

Note that, even though the user logged out, you won't be prompted for a passwort if you login again. To fully understand why, please checkout the [approuter documentation](https://www.npmjs.com/package/@sap/approuter#logout-property)
