### ISSUE TITLE
cf deploy fails in standalone-portal-mta

### ISSUE THREAD

**Issue by deepikagupta31** [SAP-samples/multi-cloud-html5-apps-samples#29]
On executing _`cf deploy mta_archives/standalone-portal-mta_1.0.0.mtar`_ fails with following error
<img width="1351" alt="Screenshot 2021-09-14 at 12 46 31 PM" src="https://user-images.githubusercontent.com/12969967/133213033-63449ae1-5e8a-44c0-ae35-7078a273be96.png">

`Service operation failed: Controller operation failed: 404 Updating service "standaloneportalmta_portal" failed: Not Found: Error creating service "standaloneportalmta_portal" from offering "portal" and plan "standard": Service plan standard not found. `

**Comment by IObert** [comment]
It seems to me that you try to deploy a sample from an older state of this repo. 

Please note that the "portal/standard" service plan is not available in trial any longer as it's deprecated. (For paying customer, it is still available). This sample is not available here anymore for exactly that reason.

**Comment by deepikagupta31** [comment]
Thank you for the response. My requirement was similar to add a sapUI5 app into the launchpad as a tile with standalone app router configurations. Can we use launchpad service with standard plan?

**Comment by IObert** [comment]
There is no service instance of the Launchpad service - there's just a subscription. Please refer to [this post](https://blogs.sap.com/2020/06/22/understanding-the-nuts-and-bolts-of-sap-fiori-development-for-cloud-foundry/) for the difference between the possible options.

If you need to use a standalone approuter, you need to include the Fiori app manually to the Launchpad catalog. Have a look [at this tutorial](https://developers.sap.com/tutorials/cp-portal-cloud-foundry-new-sapui5.html) that shows a similar flow.

**Comment by deepikagupta31** [comment]
Thank you, I got clear idea now
