### ISSUE TITLE
React with react-route-dom example

### ISSUE THREAD

**Issue by luizcarlospedrosogomes** [SAP-samples/multi-cloud-html5-apps-samples#31]
HI @IObert can you tell us or provide an example with reactc and react-route-dom, I have doubts how a SPA is inside the launchpad?

**Comment by IObert** [comment]
Hi,
Good question. I have to say that there are currently no plans to publish such a sample code, and I'm not sure if it makes much sense as the Launchpad service currently doesn't recognize non SAPUI5 apps.
Generally speaking, you can always follow the approach of the [managed-html5-runtime-basic-mta](https://github.com/SAP-samples/multi-cloud-html5-apps-samples/tree/main/managed-html5-runtime-basic-mta) and embed the app as an [URL app](https://developers.sap.com/tutorials/cp-portal-cloud-foundry-url-applaunchpad.html) manually in an FLP.

I've done something similar in this post here as well: <https://blogs.sap.com/2020/02/03/cloudfoundryfun-11-integrate-a-react-app-in-the-fiori-launchpad/>

I'll keep the issue open for now to have a discussion here in case others want to chime in.

**Comment by luizcarlospedrosogomes** [comment]
Are you telling me that the BTP launchpad service only supports SAPUI5?

There are some examples of react apps with launchpad service, all without react-route-dom, and the service itself allows you to include HTML5 apps.

I got confused

**Comment by IObert** [comment]
I'm saying that non-SAPUI5 apps can only be embedded as URLs apps :)

**Comment by luizcarlospedrosogomes** [comment]
using managed-html5-runtime-basic-mta 
![image](https://user-images.githubusercontent.com/9791364/145200958-0a0cba66-59e2-41d0-9b70-76bbe1682827.png)

![image](https://user-images.githubusercontent.com/9791364/145201111-c59e497a-fd76-4e1f-89e8-0c3bee7e3df1.png)

It looks for the static folder of the root of the portal, when it should look for the subfolder

**Comment by IObert** [comment]
I recommend reading the blog post I linked above. That one describes more details

**Comment by luizcarlospedrosogomes** [comment]
I tried 
https://blogs.sap.com/2020/02/03/cloudfoundryfun-11-integrate-a-react-app-in-the-fiori-launchpad/

![image](https://user-images.githubusercontent.com/9791364/145229120-914a506b-9bf0-4fac-ace6-80772c423424.png)

**Comment by luizcarlospedrosogomes** [comment]
![appreactLaunchpadService](https://user-images.githubusercontent.com/9791364/145255355-6dd0ad41-347c-4b01-abb3-eedcfaa40435.gif)

After some adjustments I managed to deploy the "launchpad service" but it generated two nodejs services in BTP.

The "react-route-dom" worked.

The question that remains is how not to generate these services, it doesn't make sense for a static app to have a nodejs service?

**Comment by IObert** [comment]
To which two services are you referring to?

**Comment by luizcarlospedrosogomes** [comment]
these services
![image](https://user-images.githubusercontent.com/9791364/145390078-6d73ef33-247d-43f9-aa8f-8f267a5a8976.png)

**Comment by IObert** [comment]
Ah, I see. Technically, these are called "apps" in Cloud Foundry as the term "services" is used for something else. Yes, you don't need them as the approuter isn't needed when you use the managed approuter and the ui_deployer can be substituted as well. For the details, I would refer you to this [blog post](https://blogs.sap.com/2020/10/02/serverless-sap-fiori-apps-in-sap-cloud-platform/) of mine.

**Comment by luizcarlospedrosogomes** [comment]
tanks @IObert

**Comment by luizcarlospedrosogomes** [comment]
example in react 
https://github.com/luizcarlospedrosogomes/cf-app-serverless-example
