### ISSUE TITLE
The redirect_uri has an invalid domain

### ISSUE THREAD

**Issue by nocin** [SAP-samples/multi-cloud-html5-apps-samples#43]
Hi @nicoschoenteich,

just created a fresh BTP Trial Account, followed the instructions and successfully deployed this sample.
But when opening the URL from the approuter I just get an error: **The redirect_uri has an invalid domain.**

Approuter: https://4ec1cd90trial-dev-html5-app-router.cfapps.us10-001.hana.ondemand.com/

Error: https://4ec1cd90trial.authentication.us10.hana.ondemand.com/oauth/authorize?response_type=code&client_id=sb-html5_app_repo_router!t115636&redirect_uri=https%3A%2F%2F4ec1cd90trial-dev-html5-app-router.cfapps.us10-001.hana.ondemand.com%2Flogin%2Fcallback

![grafik](https://user-images.githubusercontent.com/35531968/200617665-fba2cb5d-df15-44a8-9cc6-a6b776f5837a.png)

Seems like the login process is working, but then the approuter can't forward to the actual frontend app.

I tried to fix this error by setting manually a redirect uri in the xs-security.json (like it is done when testing a CAP app from [BAS](https://cap.cloud.sap/docs/node.js/authentication#-running-approuter))

```
  "oauth2-configuration": {
    "redirect-uris": [
      "https://*.us10-001.hana.ondemand.com"
    ]
  }
```
But still no success...
![grafik](https://user-images.githubusercontent.com/35531968/200613037-6a91488a-1d12-42e3-8007-95af15153f2b.png)

Can you confirm that this sample is still working? I saw in another issue you confirmed it working in March this year.
And I also remember using this sample at the beginning of 2022.

best regards
Nico

**Comment by nicoschoenteich** [comment]
Hi @nocin,
Can you try `https://*.us10-001.hana.ondemand.com/login/callback` as the redirect uri (attaching `/login/callback`)?
Which sample in this repo are you using?

**Comment by nocin** [comment]
Hi @nicoschoenteich,

thanks for your quick reply! And sorry for forgetting the most import information.... I'm using the sample: 
**standalone-approuter-html5-runtime-mta-hello-world**

You are right, with `https://*.us10-001.hana.ondemand.com/login/callback` it works. 
Also, when using `https://*.us10-001.hana.ondemand.com/**`. So I missed the two * at the end during my test...

But when removing the redirect uri completely, it does not work anymore. At least in my test. So it seems to be mandatory to provide this value? This is new to me and I could not find any information on that (besides the cap docs, but there the step is for hybrid testing).
If you can confirm this, it also means, the provided sample does not work out of the box anymore.

BR
Nico

**Comment by nicoschoenteich** [comment]
Hi @nocin,
I'm glad that works, yes seems like the redirect uri is a mandatory value now. I also noticed that a few weeks ago, but wasn't sure whether that was something project specific back then. I will update the samples accordingly.

**Comment by jasplil** [comment]
Hi @nicoschoenteich I also encountered the same problem with the url configured as instructed. Any idea why? Many thanks!

**Comment by nicoschoenteich** [comment]
Hi @jasplil, can you share your `xs-security.json` (blurring any sensitive information)? Also, did you update your xsuaa instance with the new configuration?

**Comment by AndreyTk** [comment]
Hi @nicoschoenteich. I have the same problem for mta app. Here is my xs-security.json file. 
What could be wrong?

```
{
  "xsappname": "paymon",
  "tenant-mode": "dedicated",
  "description": "Security profile of called application",
  "scopes": [],
  "role-templates": [],
  "oauth2-configuration": {
    "redirect-uris": [
      "https://*.cfapps.eu10-004.hana.ondemand.com/login/callback",
      "https://*.cfapps.eu10-004.hana.ondemand.com/**"
    ]
  }
}
```

**Comment by yuray76** [comment]
Hello @AndreyTk!
It seems that xsuaa service of mta+html5 project does not see xs-security.json file. Try to add this to mta.yaml 
```
resources:
- name: paymon-uaa
  type: org.cloudfoundry.managed-service
  parameters:    
    config:
      tenant-mode: dedicated
      xsappname: paymon-${space-guid}
      oauth2-configuration:
        redirect-uris: [https://*.cfapps.eu10-004.hana.ondemand.com/**]
    service: xsuaa
    service-plan: application  
```

**Comment by AndreyTk** [comment]
Hi @yuray76
Yes, this works for me! I added oauth2 configuration in mta.yaml with params:
```
 oauth2-configuration:
        redirect-uris: [https://*.cfapps.eu10-004.hana.ondemand.com/**]
```
Thank you!
