### ISSUE TITLE
Why do we need destinations for uploading content to the repo as opposed to use the concept of bindings?

### ISSUE THREAD

**Issue by piejanssens** [SAP-samples/multi-cloud-html5-apps-samples#49]
It feels strange and not well-designed if we need to create these two destinations just for the sake of uploading content to the repository. Why is this and why doesn't SAP change the repo functionality so that we can achieve the same through bindings?

https://github.com/SAP-samples/multi-cloud-html5-apps-samples/blob/main/managed-html5-runtime-basic-mta/mta.yaml#L12-L35

**Comment by nicoschoenteich** [comment]
Hi @piejanssens,
You can actually use the `html5-apps-repo` service to host and run your apps and then consume it through service bindings by binding a (standalone) approuter to it. I did it in this [Devtoberfest session](https://www.youtube.com/watch?v=Jbq6zaKEUyY). I personally haven't seen it done with a managed approuter. I will do some research and get back to you and/or provide a sample.
Best, Nico

**Comment by piejanssens** [comment]
@nicoschoenteich Great, thanks for looking into this. I'm (currently) in the managed approuter scenario (SAP Work Zone). 
I hope to get a better understanding of this setup.

It's not clear what process is using these destinations (and at which moment), furthermore how does that process know the name of the destination? We only set the name without further reference to it and it's not following a specific naming convention...

**Comment by nicoschoenteich** [comment]
Hi @piejanssens, looks like you always need a destination to expose html5 apps to the **managed** approuter:
![Screenshot 2022-11-29 at 13 48 48](https://user-images.githubusercontent.com/65965098/204533392-72450f1f-a994-4f19-81cb-38a8a35181ed.png)

That destination has to include the service key information from the `html5-apps-repo` service instance.

It looks like the managed approuter actively scans the subaccount for these types of destinations. That is why the destination name is referenced only once in the mta.yaml. The `sap.cloud.service` parameter is also mandatory (removing it removes the app to the managed approuter).

Hope this helps!

Best, Nico

**Comment by piejanssens** [comment]
Thanks Nico

I would argue that in the concept of CF's service/application bindings, the managed approuter (portal/workzone instance) could access all repo hosts that are bound to the instance... Could you check internally why it's not setup this way and if this would not be a logical improvement?

P.S. I noticed that the `sap.cloud.service` is used as categorisation for a common business solution. This should ideally be aligned with the MTA id, instead of using hardcoded 'basic.service'.

**Comment by gregorwolf** [comment]
Regarding sap.cloud.service I've posted a question last year: [Best practice naming for sap.app/id and sap.cloud/service in manifest.json](https://answers.sap.com/questions/13450453/best-practice-naming-for-sapappid-and-sapcloudserv.html)

**Comment by nicoschoenteich** [comment]
Hi @piejanssens, I agree that the current architecture is not the most intuitive. I think I don't get your desired pattern 100%, though.

> the managed approuter (portal/workzone instance) could access all repo hosts that are bound to the instance

Which "bound instance" are you referring to? Is the managed approuter bound to any instance? As far as I understood the approuter is sort of an invisible application that devs cannot actively bind to services.

Regarding the `sap.cloud.service`: Looks like there are no strict guidelines as to how business solutions should be named (see @gregorwolf's question). Your suggestion @piejanssens sounds like a good idea.

**Comment by piejanssens** [comment]
@nicoschoenteich That is indeed what I should have said: create a binding between the managed approuter and the repo host instance. That should provide all the necessary connectivity details for the approuter to access the application resources from the html5 repo host.

**Comment by nicoschoenteich** [comment]
Hi @piejanssens, ok, got it. I do like the idea, but let's get specific: How would you bind the `html5-apps-repo` instance to the managed approuter? The managed approuter is invisible to the user, which is the whole point - it is managed. Any ideas?

**Comment by piejanssens** [comment]
No, right. I'm sure that this would need a change in one or more BTP CF components, but IMO it's worth starting the discussion. The current approach is cumbersome and obscure.

**Comment by nicoschoenteich** [comment]
Hi @piejanssens, thanks again for your valid input. Internal discussions on this are ongoing - unfortunately nothing I can share at this point.
