### ISSUE TITLE
The request for authorization was invalid

### ISSUE THREAD

**Issue by 0anton** [SAP-samples/multi-cloud-html5-apps-samples#50]
Dear colleagues,

I'm trying to deploy basic HTML5 app following the tutorial https://github.com/SAP-samples/multi-cloud-html5-apps-samples/tree/main/managed-html5-runtime-basic-mta

I use commands to deploy the app:

```
mbt build -t ./
cf deploy ./mta_archives/hello-world_1.0.0.mtar
```
The complete w/o error (see the full output below).

I'm trying to access the URL I get from commands
```
cf html5-list -di hello-world-destination-service -u --runtime cpp
or 
cf html5-list -di hello-world-destination-service -u --runtime launchpad
```

Those are:

https://test-tdo.cpp.cfapps.sap.hana.ondemand.com/b3b4baed-66e6-4dcc-b538-61b3e030b02b.basicservice.helloworld-1.0.0/

https://test-tdo.launchpad.cfapps.sap.hana.ondemand.com/b3b4baed-66e6-4dcc-b538-61b3e030b02b.basicservice.helloworld-1.0.0/

Both URLs show the error

_No client with requested id: sb-launchpad-dt-approuter!t119
Authorization Request Error
There was an error. The request for authorization was invalid._

I added the CPP entitlement to my project.

Deployment script:
```
cf deploy ./mta_archives/hello-world_1.0.0.mtar
Deploying multi-target app archive ./mta_archives/hello-world_1.0.0.mtar in org test-tdo / space test-tdo as anton.golubev@sap.com...

Uploading 1 files...
  /home/d057039/multi-cloud-html5-apps-samples/managed-html5-runtime-basic-mta/mta_archives/hello-world_1.0.0.mtar
OK
Operation ID: 31a98740-766d-11ed-8440-eeee0a9b1cd5
Deploying in org "test-tdo" and space "test-tdo"
Detected MTA schema version: "3"
Detected deployed MTA with ID "hello-world" and version "1.0.0"
Detected new MTA version: "1.0.0"
Deployed MTA version: "1.0.0"
Processing service "hello-world_html_repo_host"...
Service key "hello-world_ui_deployer-hello-world_html_repo_host-credentials" for service "hello-world_html_repo_host" will not be deleted, as the option for deleting discontinued service keys is not specified!
Service key "hello-world-destination-content-hello-world_html_repo_host-credentials" for service "hello-world_html_repo_host" will not be deleted, as the option for deleting discontinued service keys is not specified!
Service key "hello-world_html_repo_host-key" for service "hello-world_html_repo_host" will not be updated, as the option for deleting discontinued service keys is not specified!
Processing service "hello-world_uaa"...
Setting service "hello-world_uaa" parameters from "xs-security.json"
Updating service "hello-world_uaa"...
Processing service "hello-world-destination-service"...
1 of 1 done
Service key "hello-world-destination-content-hello-world_uaa-credentials" for service "hello-world_uaa" will not be deleted, as the option for deleting discontinued service keys is not specified!
Service key "hello-world_uaa-key" for service "hello-world_uaa" will not be updated, as the option for deleting discontinued service keys is not specified!
```
```
cf s
Getting services in org test-tdo / space test-tdo as anton.golubev@sap.com...

name                              service           plan          bound apps   last operation     broker
           upgrade available
hello-world-destination-service   destination       lite                       update succeeded   sm-destination-service-broker-52b0057d-bd1f-469b-9dfe-87da314888bc
hello-world_html_repo_host        html5-apps-repo   app-host                   create succeeded   sm-html5-apps-repo-sb-783f875c-90ed-488a-9dcb-01d834a1e8ac
```

Would you please help me to understand and fix the problem?

Kind regards,
Anton
anton.golubev@sap.com

**Comment by nicoschoenteich** [comment]
Hi @0anton,
Have you subscribed to either the Launchpad or Cloud Portal service in your subaccount? You say you have "added the CPP entitlement to my project" - I am not exactly sure what that means. Entitlements happen on subaccount level. You need to have a service entitled before you can subscribe to it or create instances of it.
Best, Nico

**Comment by 0anton** [comment]
![image](https://user-images.githubusercontent.com/17309924/206763702-5249855a-c153-4411-a291-d76d2f52cb2f.png)

Hi @nicoschoenteich,
Thank you for response!

Yes, my subaccount is subscribed to both Launchpad and Cloud Portal service.

Sorry to using the mis-leading terminology. CPP is the domain name the BTP uses for exposing Cloud Portal resources (https://*.cpp.cfapps.sap.hana.ondemand.com). I have mistakenly thought it is also a valid conversational shortcut for Portal Service.

Project is also a (wrong) term by me from another domain. On GCP it is a lowest level to structure resources. I meant a BTP sub-account.

See also https://sap.stackenterprise.co/questions/27084 to the same.

**Comment by nicoschoenteich** [comment]
Hi @0anton,
From the screen shot I can see that the services are entitled, which means you are allowed to use them, but are you sure you actually subscribed? You can check under "Instances and Subscriptions".
Best, Nico

**Comment by 0anton** [comment]
_Launchpad_ is at least subscribed. I've created it manually, although was not sure if it is needed. I used to run hyperscaler examples with Terraform descriptors, which bring all necessary infrastructure with the self-contained projects.
So, I need complete instructions, if something else is assumed to be pre-configured.
![image](https://user-images.githubusercontent.com/17309924/206928936-20851a83-4014-4e35-8d6c-facdf7e9c412.png)

**Comment by nicoschoenteich** [comment]
Hi @0anton,
Thanks for the screen shot. I know it's kind of confusing, but you created an instance of the Launchpad (also referred to as `Launchpad module`, which is something else than **subscribing** to the Launchpad service. Basically speaking, you can create multiple instances of one service in a subaccount, but you can only subscribe to an application once - that's the user's perspective at least, there are other technical and architectural differences, too.
Anyway, when clicking **Create** under "Instances and Subscriptions", make sure to select the service plan that has `subscription` in the title or description. Then try to redeploy your application.
Hope this helps. Let me know if you have more questions.
Best, Nico

**Comment by 0anton** [comment]
Morning, @nicoschoenteich!
Thanks for further tipps! I've deleted _Launchpad_ service instance, as told, and trying to create a _Service Plan_ subscription. However, in plans, where is only `standard` thing, which causes the creation of already tried Service Instance:
![image](https://user-images.githubusercontent.com/17309924/207032358-4eaa6aab-5a77-4551-8dfc-34d127fde149.png)

Same situation is with the _Portal_:
![image](https://user-images.githubusercontent.com/17309924/207032916-9f6086db-9c36-477e-9f1b-45444de68d6c.png)


My current global account assigned services:
![image](https://user-images.githubusercontent.com/17309924/207034137-3af928ee-d77b-4889-ae86-32311f2fd0ed.png)

Interestingly, in _Applications_, where is a _Launchpad Service_ with a tech name `SAPLaunchpad`. Maybe this is something I need?

![image](https://user-images.githubusercontent.com/17309924/207035146-20633e17-fcdc-4c5e-824d-0c92b5bd1812.png)

Okey, now I've got the _Launchpad Service_ subscription:
![image](https://user-images.githubusercontent.com/17309924/207035239-48b5d119-6e92-4435-a405-f4322a421ad2.png)

**Comment by nicoschoenteich** [comment]
Hi @0anton,
Yes exactly, you want the application version of the Launchpad, which you can subscribe to. Can you try to redeploy and see if the initial error persists?

**Comment by 0anton** [comment]
Funny enough, after subscribing to SAP Launchpad service, I've lost the possibility to create the most of resources in the organisation.

I'm not sure, why, because the plans are still available in the org:
- "xsuaa" and plan "application": Service plan application not found.
![image](https://user-images.githubusercontent.com/17309924/207042536-d9a73bd3-8eed-4ffc-9eec-9b3379b3078b.png)

- from offering "html5-apps-repo" and plan "app-host":
![image](https://user-images.githubusercontent.com/17309924/207042778-dc0721bf-28ce-468b-9a57-985a1febe023.png)



```
cf deploy ./mta_archives/hello-world_1.0.0.mtar
Deploying multi-target app archive ./mta_archives/hello-world_1.0.0.mtar in org tdo-dev / space tdo-dev as anton.golubev@sap.com...


Previously uploaded file hello-world_1.0.0.mtar with same digest detected, new upload will be skipped.
Operation ID: 15f1cabe-7a16-11ed-88d3-eeee0a86dba8
Deploying in org "tdo-dev" and space "tdo-dev"
Detected MTA schema version: "3"
No deployed MTA detected - this is initial deployment of MTA with ID "hello-world"
Detected new MTA version: "1.0.0"
Processing service "hello-world_uaa"...
Setting service "hello-world_uaa" parameters from "xs-security.json"
Creating service "hello-world_uaa" from MTA resource "hello-world_uaa"...
Service operation failed: Controller operation failed: 404 Updating service "hello-world_uaa" failed: Not Found: Error creating service "hello-world_uaa" from offering "xsuaa" and plan "application": Service plan application not found.
Proceeding with automatic retry... (3 of 3 attempts left)
Processing service "hello-world-destination-service"...
Creating service "hello-world-destination-service" from MTA resource "hello-world-destination-service"...
Creating service "hello-world_uaa" from MTA resource "hello-world_uaa"...
Service operation failed: Controller operation failed: 404 Updating service "hello-world_uaa" failed: Not Found: Error creating service "hello-world_uaa" from offering "xsuaa" and plan "application": Service plan application not found.
Processing service "hello-world_html_repo_host"...
Creating service "hello-world_html_repo_host" from MTA resource "hello-world_html_repo_host"...
Service operation failed: Controller operation failed: 404 Updating service "hello-world_html_repo_host" failed: Not Found: Error creating service "hello-world_html_repo_host" from offering "html5-apps-repo" and plan "app-host": Service plan app-host not found.
Proceeding with automatic retry... (2 of 3 attempts left)
Creating service "hello-world_html_repo_host" from MTA resource "hello-world_html_repo_host"...
Creating service "hello-world_uaa" from MTA resource "hello-world_uaa"...
Service operation failed: Controller operation failed: 404 Updating service "hello-world_uaa" failed: Not Found: Error creating service "hello-world_uaa" from offering "xsuaa" and plan "application": Service plan application not found.
Service operation failed: Controller operation failed: 404 Updating service "hello-world_html_repo_host" failed: Not Found: Error creating service "hello-world_html_repo_host" from offering "html5-apps-repo" and plan "app-host": Service plan app-host not found.
Error monitoring creation or update of services: Error creating service "hello-world-destination-service" from offering "destination" and plan "lite": Service broker error: Service broker destination-service-broker failed with: Failed to create a destination service instance with the user provided configuration.
Proceeding with automatic retry... (1 of 3 attempts left)
Creating service "hello-world_uaa" from MTA resource "hello-world_uaa"...
Creating service "hello-world-destination-service" from MTA resource "hello-world-destination-service"...
Creating service "hello-world_html_repo_host" from MTA resource "hello-world_html_repo_host"...
Service operation failed: Controller operation failed: 404 Updating service "hello-world_uaa" failed: Not Found: Error creating service "hello-world_uaa" from offering "xsuaa" and plan "application": Service plan application not found.
Service operation failed: Controller operation failed: 404 Updating service "hello-world_html_repo_host" failed: Not Found: Error creating service "hello-world_html_repo_host" from offering "html5-apps-repo" and plan "app-host": Service plan app-host not found.
Process failed.
Use "cf deploy -i 15f1cabe-7a16-11ed-88d3-eeee0a86dba8 -a abort" to abort the process.
Use "cf deploy -i 15f1cabe-7a16-11ed-88d3-eeee0a86dba8 -a retry" to retry the process.
Use "cf dmol -i 15f1cabe-7a16-11ed-88d3-eeee0a86dba8" to download the logs of the process.
```

**Comment by nicoschoenteich** [comment]
Hm, looks like it might be a good idea to delete all instances and service key from the previously deployed MTA. Maybe the initial error is blocking updates or new deployments.

**Comment by 0anton** [comment]
After deleting all resources from the sub-account and moving to a completely new sub-account, it now breaks in _destination service_ creation:

```
cf deploy ./mta_archives/hello-world_1.0.0.mtar
Deploying multi-target app archive ./mta_archives/hello-world_1.0.0.mtar in org tdo / space tdo as anton.golubev@sap.com...


There is an ongoing operation for multi-target app hello-world. Do you want to abort it? (y/n)> y
Executing action 'abort' on operation 3fa137bd-7a17-11ed-9d5a-eeee0a84b865...
OK
Previously uploaded file hello-world_1.0.0.mtar with same digest detected, new upload will be skipped.
Operation ID: e70cb769-7a17-11ed-9d5a-eeee0a84b865
Deploying in org "tdo" and space "tdo"
Detected MTA schema version: "3"
No deployed MTA detected - this is initial deployment of MTA with ID "hello-world"
Detected new MTA version: "1.0.0"
Processing service "hello-world_html_repo_host"...
Creating service "hello-world_html_repo_host" from MTA resource "hello-world_html_repo_host"...
Processing service "hello-world_uaa"...
Setting service "hello-world_uaa" parameters from "xs-security.json"
Processing service "hello-world-destination-service"...
Creating service "hello-world_uaa" from MTA resource "hello-world_uaa"...
Creating service "hello-world-destination-service" from MTA resource "hello-world-destination-service"...
1 of 1 done
Error monitoring creation or update of services: Error creating service "hello-world-destination-service" from offering "destination" and plan "lite": Service broker error: Service broker destination-service-broker failed with: Failed to create a destination service instance with the user provided configuration.
1 of 1 done
Proceeding with automatic retry... (3 of 3 attempts left)
Creating service "hello-world-destination-service" from MTA resource "hello-world-destination-service"...
Error monitoring creation or update of services: Error creating service "hello-world-destination-service" from offering "destination" and plan "lite": Service broker error: Service broker destination-service-broker failed with: Failed to create a destination service instance with the user provided configuration.
Creating service key "hello-world_html_repo_host-key" for service "hello-world_html_repo_host"...
Creating service key "hello-world_uaa-key" for service "hello-world_uaa"...
Proceeding with automatic retry... (2 of 3 attempts left)
Creating service "hello-world-destination-service" from MTA resource "hello-world-destination-service"...
Error monitoring creation or update of services: Error creating service "hello-world-destination-service" from offering "destination" and plan "lite": Service broker error: Service broker destination-service-broker failed with: Failed to create a destination service instance with the user provided configuration.
Proceeding with automatic retry... (1 of 3 attempts left)
Creating service "hello-world-destination-service" from MTA resource "hello-world-destination-service"...
Error monitoring creation or update of services: Error creating service "hello-world-destination-service" from offering "destination" and plan "lite": Service broker error: Service broker destination-service-broker failed with: Failed to create a destination service instance with the user provided configuration.
Process failed.
Use "cf deploy -i e70cb769-7a17-11ed-9d5a-eeee0a84b865 -a abort" to abort the process.
Use "cf deploy -i e70cb769-7a17-11ed-9d5a-eeee0a84b865 -a retry" to retry the process.
Use "cf dmol -i e70cb769-7a17-11ed-9d5a-eeee0a84b865" to download the logs of the process.
```


Destination service with the plan _lite_ is added to the sub-account:
![image](https://user-images.githubusercontent.com/17309924/207044707-2131f1d5-cb01-4fee-a299-0cc0489fa437.png)

Launchpad is subscribed:

![image](https://user-images.githubusercontent.com/17309924/207045143-cc3ffa61-2df1-4c48-ad38-6833e85815b3.png)

If you think it will be more efficient, we can have a short call.

**Comment by 0anton** [comment]
Still not working.

**Comment by 0anton** [comment]
After a week the deployment of destination has self-recovered after re-deployment and the app is now accessible from the Internet:
![image](https://user-images.githubusercontent.com/17309924/208485245-c68f68ec-d3d3-4bcd-acc3-b5e45e26d9e4.png)
Works!
