### ISSUE TITLE
URL is broken

### ISSUE THREAD

**Issue by superwangnan** [SAP-samples/multi-cloud-html5-apps-samples#52]
Hi team,
In this page https://github.com/SAP-samples/multi-cloud-html5-apps-samples/tree/main/optional-self-hosted-backend when you click the link to "[managed-html-runtime-fiori-mta](https://github.com/SAP-samples/multi-cloud-html5-apps-samples/blob/main/managed-html5-runtime-fiori-mta)" project. You will find the link is broken. Who can help to recover it?
Thanks~

**Comment by nicoschoenteich** [comment]
Thanks for pointing it out!
