### ISSUE TITLE
HTML5 apps used as UserTask in a Workflow

### ISSUE THREAD

**Issue by JeremyChabert** [SAP-samples/multi-cloud-html5-apps-samples#6]
Hello,
First of all, thanks for the examples provided, they are immensely helpful.
Regarding my request, we are currently trying to deploy a Workflow on Cloud Foundry that is using Custom HTML5 apps as User Task. 
Even if we succeed to deploy the HTML5 app in a repo, we now have issues with the Inbox app to retrieve the HTML5 app out of that repo and to display it.
To give a small insight of our project, it's structured as follow:
``` .txt
my-project
 |__ workflow
      |__ forms
      |__ workflows
      |__ scripts
      |__ ...
 |__ workflowApprouter
 |__ com.usertask
       |__ webapp
 |__ html5Deployer
 |__ FioriLaunchpad
```
Could this scenario be a future sample of that github repository ?
Thanks,
Best regards,
Jérémy.

**Comment by vbalko** [comment]
What is the error in console log? I recently made same scenario for a customer and made it working (after few days and hundreds of try - error cycles).
One of my mistakes was that In the xs-app.json to the route for bpmworkflow path I added actual URL from service key instead of just variable name workflow_service_rest.

This error caused, that my custom UI app wasnt loaded and generic UI was shown.

**Comment by vbalko** [comment]
and also - there is new way to deploy custom UI apps into the application repository - without constructing additional nodejs application.
Marcus is speaking about this in a video [https://www.youtube.com/watch?v=emnl-y9btdU&t=237s](url)

You can also get working example when using yeomans generator https://github.com/SAP/generator-easy-ui5 or standard MTAR HTML5 generator in Business Application Studio.

It is better way because the standard builder takes care of deploying and no additional nodejs app is needed - which will get your apps limit in subaccounts limit.

**Comment by JeremyChabert** [comment]
> and also - there is new way to deploy custom UI apps into the application repository - without constructing additional nodejs application.
> Marcus is speaking about this in a video [https://www.youtube.com/watch?v=emnl-y9btdU&t=237s](url)
> 
> You can also get working example when using yeomans generator https://github.com/SAP/generator-easy-ui5 or standard MTAR HTML5 generator in Business Application Studio.
> 
> It is better way because the standard builder takes care of deploying and no additional nodejs app is needed - which will get your apps limit in subaccounts limit.


Hello,

Thanks for your answer and the youtube link provided.

The console shows this when I open my inbox:
![image](https://user-images.githubusercontent.com/47522598/92571274-36aa7600-f283-11ea-8846-7bb937dc74af.png)

I indeed used the uideployer for my html5 app.
I have created the HTML5 project in Business application studio, using yo and easy-ui5 chosing an HTML5 app on Cloud foundry.
This is the folder `com.bMx.usertask`, then I wrap it into an *uimodule.zip* and the result is placed in folder `html5deployer` under a subfolder called `resources`

I think maybe it has something to do with the route but I can't picture what
Here's my project content and the depoyment log
![image](https://user-images.githubusercontent.com/47522598/92571803-e1229900-f283-11ea-8494-89cf014d78a1.png)

And here's the content of my xs-app.json in the `workflowApprouter` folder
```.json
{
    "welcomeFile": "/cp.portal",
    "authenticationMethod": "route",
    "routes": [
        {
            "source": "^/bpmworkflowruntime/(.*)$",
            "target": "/$1",
            "service": "com.sap.bpm.workflow",
            "endpoint": "workflow_rest_url"
        },
        {
            "source": "^(.*)",
            "target": "$1",
            "authenticationType":"xsuaa",
            "service": "html5-apps-repo-rt"
        }
    ]
}
```

**Comment by vbalko** [comment]
Hello Jeremy,

the error is typical error, when something prevents successfull consuming UI5 app from repository. I can see, that your xs-app.json looks ok, but I don`t know if it is ok to have these routes in approuters xs-app file. I have them in UI app xs-app.json.

I created today github repository with functioning project as you requested in a first post. You can find it in repository [https://github.com/vbalko/SAP-mta-wf-customUI-sample](https://github.com/vbalko/SAP-mta-wf-customUI-sample)

I also wrote a veeery long blog post describing process how I created that project. If you are interested - you can do same project by yourself. 
[https://vbalko.blogspot.com/2020/09/create-workflow-mtar-application-with.html](url)

If you still want to know what is wrong with your code - put it to the github and I will try to clone it and inspect by myself. But I cannot say when I`m gonna do it. It is quite busy recently.

**Comment by JeremyChabert** [comment]
Hello,
I will look at the project you kindly provided and also the blog.
I'll let you know if it solves my issue or not.
Thanks for the suggestion of sharing my project. If I find myself in a dead end with all the help you already provided, I'll share my source with you but I don't want to add you some extra work if I can solve it on my own.
Have a nice day/evening.
I'll keep you updated

**Comment by JeremyChabert** [comment]
Sooooooo... **It works now !**
Based on your mta.yaml, I have just changed my mta.yaml file and the build parameters of the UI5 module and I finally got my UI working.
I can not thank you enough for providing me your source.
@IObert, maybe the example provided by @vbalko can be part of the repo for the custom UI in a workflow scenario on CF.

**Comment by vbalko** [comment]
I like to hear, that you finally resolved your issue. What was part you were missing?

**Comment by JeremyChabert** [comment]
I think I misplaced the xs-app.json as you stated. Then I had an issue with the instance of destination service that was not bound correctly.
Once this fixed, it worked perfectly.
